kind: Namespace
apiVersion: v1
metadata:
  name: lab1-namespace
  labels:
    name: lab1-namespace

---

apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: lab1-namespace
  labels:
    app: vault
spec:
  containers:
  - name: vault
    image: hashicorp/vault
