apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: location-africa-ippool
spec:
  cidr: 192.168.0.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: location == "Africa"

---

apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: location-europe-ippool
spec:
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: location == "Europe"


