apiVersion: v1
kind: Namespace
metadata:
  name: lab2-namespace
  labels:
    name: lab2-namespace

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: lab2-namespace
  labels:
    tier: frontend
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
      environment: dev
  template:
    metadata:
      labels:
        tier: frontend
        environment: dev
    spec:
      containers:
        - name: frontend
          image: ifilyaninitmo/itdt-contained-frontend:master
          env:
            - name: REACT_APP_USERNAME
              value: "andreysoldatov"
            - name: REACT_APP_COMPANY_NAME
              value: "Service solution"
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-frontend
  namespace: lab2-namespace
  labels:
    service: frontend
spec:
  selector:
    tier: frontend
    environment: dev
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
